basePath: /
definitions:
  models.Transport:
    properties:
      description:
        description: Description
        type: string
      id:
        description: |-
          The id of the transport.

          required: true
        type: string
      modality:
        description: Modalirt
        type: string
      name:
        description: |-
          The name of the pet.

          required: true
          pattern: \w[\w-]+
          minimum length: 3
          maximum length: 50
        type: string
    required:
    - description
    - modality
    - name
    type: object
host: localhost:8080
info:
  contact: {}
  title: User API documentation
  version: 1.0.0
paths:
  /:
    get:
      description: get all transport
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Transport'
            type: array
        "404":
          description: Not Found
          schema:
            type: object
      summary: Get all users
      tags:
      - Transports
    post:
      consumes:
      - application/json
      description: Create new transport
      parameters:
      - description: Transport Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.Transport'
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Create new transport based on paramters
      tags:
      - Transports
  /{id}:
    delete:
      description: Delete transport by ID
      parameters:
      - description: Transport ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Transport'
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
      summary: Delete one Transport
      tags:
      - Transports
    get:
      description: get transport by ID
      parameters:
      - description: Transport ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Transport'
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
      summary: Get one Transport
      tags:
      - Transports
    put:
      description: Edit transport by ID
      parameters:
      - description: Transport ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Transport'
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
      summary: Edit one Transport
      tags:
      - Transports
swagger: "2.0"
